spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/buildMate
    username: root
    password: 1234

#MyBatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true